### send a message
GET http://localhost:8001/api/channel/messages
content-type: application/json

{
  "channelID": "5e39ef67458c2b44ab410e57"
}

### send a message
GET http://localhost:8001/api/channel/messages
content-type: application/json

{
  "channelID": "5e39f313dc3f1447605ce4fb"
}