### can register
POST http://localhost:8001/api/auth/register
content-type: application/json

{
  "password": "password",
  "email": "email@gmail.com"
}

### another user
POST http://localhost:8001/api/auth/login
content-type: application/json

{
  "password": "password",
  "email": "email@gmail.com"
}

### create new channel
POST http://localhost:8001/api/channel/new
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI1ZTNhNDYxZWQ4MjJiYTI5NzU1NmI4NTEiLCJpYXQiOjE1ODEzNzM1MDYsImV4cCI6MTYxMjkzMDQzMn0.DZQBe1r-NNT-wpqKxjFphTAD2cMz9epv8aJ_334hYZE

{
  "channelName": "Channel sadsadsName"
}

### create new different channel
POST http://localhost:8001/api/channel/new
content-type: application/json

{
  "userID": "5e39ef3f458c2b44ab410e56",
  "channelName": "Channel Name TWO"
}

### send a message
POST http://localhost:8001/api/channel/messages
content-type: application/json

{
  "userID": "5e39ef3f458c2b44ab410e56",
  "channelID": "5e39f313dc3f1447605ce4fb",
  "message": "message"
}

### access token check
POST https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=ya29.ImC8B8LjZTyPN5ItQPFHoopaBPSBXPAV3C_9AJcrdPPcHlqTdQUr6QquLamArOSwX8GwAfBiEbgyFd1_NJhVGBCdpNYWQi_LLvK52uJVSI6-ssERwp4Vvdg7SaQE58WN9DA
