###
POST http://localhost:8001/api/auth/register
content-type: application/json

{
  "password": "password",
  "email": "email@gmail.com"
}
###
POST http://localhost:8001/api/auth/localhost:8001/api/auth/login
content-type: application/json

{
  "password": "password",
  "email": "email@gmail.com"
}
###
POST http://localhost:8001/api/channel/new
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI1ZTNhNDYxZWQ4MjJiYTI5NzU1NmI4NTEiLCJpYXQiOjE1ODA4NzczNDIsImV4cCI6MTYxMjQzNDI2OH0.ewiJLm6g1ZYGboXiSVOHR5bWAUAv_78nY4d7xUdkdgs

{
  "channelName": "Channel Name"
}

###
POST http://localhost:8001/api/channel/messages
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI1ZTNhNDYxZWQ4MjJiYTI5NzU1NmI4NTEiLCJpYXQiOjE1ODA4NzczNDIsImV4cCI6MTYxMjQzNDI2OH0.ewiJLm6g1ZYGboXiSVOHR5bWAUAv_78nY4d7xUdkdgs

{
  "message": "Channel Name",
  "channel": "5e3a4645d822ba297556b852"
}